# Generated by Django 3.2.3 on 2026-05-02 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название маршрута')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('start_city', models.CharField(max_length=100, verbose_name='Город отправления')),
                ('end_city', models.CharField(max_length=100, verbose_name='Город прибытия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_routes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('cats', models.ManyToManyField(related_name='travel_routes', to='cats.Cat', verbose_name='Котики')),
            ],
            options={
                'verbose_name': 'Маршрут путешествия',
                'verbose_name_plural': 'Маршруты путешествий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('arrival_date', models.DateField(verbose_name='Дата прибытия')),
                ('departure_date', models.DateField(verbose_name='Дата убытия')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок следования')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='cats.travelroute', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Точка маршрута',
                'verbose_name_plural': 'Точки маршрута',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TravelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cats.travelroute', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'unique_together': {('route', 'participant')},
            },
        ),
    ]
