# Generated by Django 3.2.3 on 2026-05-09 18:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cats', '0002_travelbooking_travelpoint_travelroute'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='travelroute',
            unique_together={('author', 'title')},
        ),
    ]
