# Generated by Django 3.2.3 on 2026-05-12 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_alter_travelroute_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название потребности')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено/куплено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='cats.cat', verbose_name='Котик')),
                ('travel_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlist_items', to='cats.travelroute', verbose_name='Связанный маршрут')),
            ],
            options={
                'verbose_name': 'Потребность кота (Wishlist)',
                'verbose_name_plural': 'Потребности котов (Wishlist)',
                'ordering': ['-created_at'],
            },
        ),
    ]
